### ISSUE TITLE
Track aspect status

### ISSUE THREAD

**Issue by pyure** [Dyonovan/TCNodeTracker#22]
Dyonovan, Node Tracker is brilliant, good work.

Feature Request:

Either a check-box beside each node in the report, or display the current amount of aspects (in addition to the max, somehow, screen-space notwithstanding.  Tooltip maybe?).   

Scenario: Frequently in early game I want to fill my wand.  So I'll filter for, say, all ignis nodes, and visit those.  Problem: I can't tell which ones I've already visited.  A checkbox or current-aspect status would fix this.

Thanks again.

**Comment by Lunatrius** [comment]
Instead of check boxes and current aspects in the node, the last time when you were around/scanned the node could be tracked.

It gives you more information than a simple check box, and should be less intensive and more accurate than active pooling of the nodes (chunks could be unloaded on multi-player, other dimensions etc).

**Comment by Dyonovan** [comment]
This is a good idea. Ive had that issue myself. I think last scanned would be the easiest and it will have to be a mouse over. I really need to redesign the interface as its getting to cramped

**Comment by Lunatrius** [comment]
`GuiListExtended` might be worth checking out for the list (`GuiKeyBindingList` for a button example because it can be tricky to get the buttons actually working).

_Just an idea, but could merge all dimensions into one list with category headers showing the dimension they're in (similar to the keybinding list) with the current dimension always on top._

**Comment by pyure** [comment]
Thanks for even looking into it sir.  Last-scanned isn't perfect but its better than nothing.
